apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-deployment
  labels:
    app: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        ports:
        - name: http
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
spec:
  type: NodePort
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30088
